export const MATCHING_EXERCISES: any = [
  { jsonFile: "Leg_Press.json", dataName: "legpress", score: 100 },
  { jsonFile: "Drag_Curl.json", dataName: "dragcurl", score: 100 },
  { jsonFile: "Plank.json", dataName: "plank", score: 100 },
  { jsonFile: "Face_Pull.json", dataName: "facepull", score: 100 },
  {
    jsonFile: "Hanging_Leg_Raise.json",
    dataName: "hanginglegraise",
    score: 100,
  },
  { jsonFile: "Seated_Leg_Curl.json", dataName: "seatedlegcurl", score: 100 },
  { jsonFile: "Preacher_Curl.json", dataName: "preachercurl", score: 100 },
  { jsonFile: "Decline_Crunch.json", dataName: "declinecrunch", score: 100 },
  {
    jsonFile: "Standing_Calf_Raises.json",
    dataName: "standingcalfraise",
    score: 97,
  },
  { jsonFile: "Leg_Extensions.json", dataName: "legextension", score: 96 },
  { jsonFile: "Lying_Leg_Curls.json", dataName: "lyinglegcurl", score: 96 },
  { jsonFile: "Hammer_Curls.json", dataName: "hammercurl", score: 95 },
  { jsonFile: "Pullups.json", dataName: "pullup", score: 92 },
  {
    jsonFile: "Sled_Overhead_Triceps_Extension.json",
    dataName: "overheadtricepsextension",
    score: 92,
  },
  { jsonFile: "Pushups.json", dataName: "pushup", score: 92 },
  { jsonFile: "Bicycling.json", dataName: "cycling", score: 88 },
  {
    jsonFile: "Triceps_Pushdown.json",
    dataName: "tricepsropepushdown",
    score: 88,
  },
  {
    jsonFile: "Incline_Cable_Chest_Press.json",
    dataName: "inclinechestpress",
    score: 87,
  },
  {
    jsonFile: "One_Arm_Lat_Pulldown.json",
    dataName: "singlearmlatpulldown",
    score: 86,
  },
  { jsonFile: "Side_Lateral_Raise.json", dataName: "lateralraise", score: 86 },
  { jsonFile: "Lying_Cable_Curl.json", dataName: "lyinglegcurl", score: 85 },
  {
    jsonFile: "Cable_Seated_Lateral_Raise.json",
    dataName: "cablelateralraise",
    score: 85,
  },
  {
    jsonFile: "Cable_Rope_Overhead_Triceps_Extension.json",
    dataName: "overheadtricepsextension",
    score: 84,
  },
  { jsonFile: "Front_Leg_Raises.json", dataName: "frontraise", score: 83 },
  {
    jsonFile: "Decline_Barbell_Bench_Press.json",
    dataName: "declinebenchpress",
    score: 83,
  },
  {
    jsonFile: "Standing_Barbell_Calf_Raise.json",
    dataName: "standingcalfraise",
    score: 83,
  },
  { jsonFile: "Cable_Preacher_Curl.json", dataName: "preachercurl", score: 83 },
  {
    jsonFile: "Rocking_Standing_Calf_Raise.json",
    dataName: "standingcalfraise",
    score: 83,
  },
  {
    jsonFile: "Machine_Bench_Press.json",
    dataName: "declinebenchpress",
    score: 82,
  },
  { jsonFile: "Calf_Press.json", dataName: "sledcalfpress", score: 82 },
  { jsonFile: "Reverse_Flyes.json", dataName: "reveasefly", score: 82 },
  {
    jsonFile: "Seated_Triceps_Press.json",
    dataName: "seatedchestpress",
    score: 82,
  },
  {
    jsonFile: "Standing_Dumbbell_Calf_Raise.json",
    dataName: "standingcalfraise",
    score: 81,
  },
  {
    jsonFile: "Decline_Dumbbell_Bench_Press.json",
    dataName: "declinebenchpress",
    score: 81,
  },
  {
    jsonFile: "Leverage_Incline_Chest_Press.json",
    dataName: "inclinechestpress",
    score: 81,
  },
  {
    jsonFile: "Barbell_Bench_Press_-_Medium_Grip.json",
    dataName: "barbellbenchpress(widegrip)",
    score: 81,
  },
  {
    jsonFile: "Cable_Chest_Press.json",
    dataName: "inclinechestpress",
    score: 81,
  },
  { jsonFile: "Front_Plate_Raise.json", dataName: "frontraise", score: 80 },
  { jsonFile: "Front_Cable_Raise.json", dataName: "frontraise", score: 80 },
  {
    jsonFile: "Dumbbell_Side_Bend.json",
    dataName: "dumbbellsidebend",
    score: 100,
  },
];
